In [1]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
IMAGE_SIZE =224
CHANNEL=3

train_datagen= ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

train_generator=  train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=64,
    class_mode='sparse'
)

Found 15000 images belonging to 15 classes.


In [3]:
for image_batch, label_batch in train_generator:
    print(image_batch[0])
    break

[[[0.06602884 0.06931257 0.04970473]
  [0.04505418 0.04537367 0.03657207]
  [0.02512971 0.03233273 0.02088808]
  ...
  [0.38129765 0.425616   0.18992817]
  [0.38116384 0.4243011  0.18900697]
  [0.38103002 0.42416728 0.18887314]]

 [[0.06589501 0.06904493 0.04943708]
  [0.04545565 0.04584205 0.03683971]
  [0.02546426 0.03253346 0.02115572]
  ...
  [0.37345564 0.41812888 0.18232277]
  [0.37332183 0.41645908 0.18116497]
  [0.37318802 0.41632527 0.18103114]]

 [[0.06285118 0.06586727 0.04625943]
  [0.042726   0.0431793  0.03397624]
  [0.02488491 0.03182028 0.02050946]
  ...
  [0.3562344  0.4099757  0.16767922]
  [0.35487604 0.4086171  0.16625376]
  [0.35454148 0.4084833  0.16598612]]

 ...

 [[0.6392966  0.59351796 0.43793547]
  [0.63849366 0.5929827  0.43766785]
  [0.6287204  0.58501285 0.4282289 ]
  ...
  [0.72508824 0.7294637  0.7107636 ]
  [0.72208333 0.7316806  0.7202508 ]
  [0.71948975 0.7426255  0.7338922 ]]

 [[0.59160566 0.5605526  0.4216125 ]
  [0.5906689  0.5596827  0.42121106]


In [4]:
validation_datagen= ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

validation_generator=validation_datagen.flow_from_directory(
    'dataset/validation',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=64,
    class_mode='sparse'
)

Found 3000 images belonging to 15 classes.


In [5]:
test_datagen= ImageDataGenerator(
    rescale=1./255,
    horizontal_flip=True,
    rotation_range=10
)

test_generator=test_datagen.flow_from_directory(
    'dataset/test',
    target_size=(IMAGE_SIZE,IMAGE_SIZE),
    batch_size=64,
    class_mode='sparse'
)

Found 3000 images belonging to 15 classes.


In [6]:
input_shape=(IMAGE_SIZE,IMAGE_SIZE, CHANNEL)
n_classes=15

model=models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size=(3,3), activation='relu'),
    layers.MaxPool2D((2,2)),
    layers.Conv2D(64,kernel_size=(3,3), activation='relu'),
    layers.MaxPool2D((2,2)),
    layers.Conv2D(64,kernel_size=(3,3), activation='relu'),
    layers.MaxPool2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPool2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPool2D((2,2)),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPool2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax')
])

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 111, 111, 32)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 109, 109, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 54, 54, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 52, 52, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 26, 26, 64)        0

In [8]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)

In [9]:
15000/64

234.375

In [10]:
3000/64

46.875

In [ ]:
history= model.fit(
    train_generator,
    steps_per_epoch=234,
    batch_size=32,
    validation_data=validation_generator,
    validation_steps=46,
    verbose=1,
    epochs=15,
)

Epoch 1/15


234/234 [==============================] - 556s 2s/step - loss: 1.8884 - accuracy: 0.3275 - val_loss: 1.5215 - val_accuracy: 0.4562
Epoch 2/15
217/234 [==========================>...] - ETA: 25s - loss: 1.2955 - accuracy: 0.5372

In [ ]:
scores=model.evaluate(test_generator)

In [ ]:
scores

In [ ]:
history

In [ ]:
history.params

In [ ]:
history.history.keys()

In [ ]:
type(history.history['loss'])

In [ ]:
len(history.history['loss'])

In [ ]:
history.history['loss'][:5]

In [ ]:
acc=history.history["accuracy"]
val_acc=history.history["val_accuracy"]

loss=history.history["loss"]
val_loss=history.history["val_loss"]

In [ ]:
val_acc


In [ ]:
acc

In [ ]:
EPOCHS=15

plt.figure(figsize=(8,8))
plt.subplot(1,2,1)
plt.plot(range(EPOCHS),acc, label="training accuracy")
plt.plot(range(EPOCHS),val_acc, label="validation accuracy")
plt.legend(loc="lower right")
plt.title("training and validation accuracy")


plt.subplot(1,2,2)
plt.plot(range(EPOCHS),loss, label="training loss")
plt.plot(range(EPOCHS),val_loss, label="validation loss")
plt.legend(loc="upper right")
plt.title("training and validation loss")
plt.show()

In [ ]:
train_generator.class_indices

In [ ]:
class_names = list(train_generator.class_indices.keys())
class_names

In [ ]:
import numpy as np


for image_batch, label_batch in test_generator:
    first_image = image_batch[0]
    first_label = int(label_batch[0])
    
    print("first image to predict")
    plt.imshow(first_image)
    print("actual label:",class_names[first_label])
    
    batch_prediction = model.predict(image_batch)
    print("predicted label:",class_names[np.argmax(batch_prediction[0])])
    
    break

In [ ]:
def predict(model, img):
    img_array=tf.keras.preprocessing.image.img_to_array(images[i])
    img_array=tf.expand_dims(img_array,0) #create a batch

    predictions=model.predict(img_array)

    predicted_class=class_names[np.argmax(predictions[0])]
    confidence=round(100*(np.max(predictions[0])),2)
    return predicted_class, confidence

In [ ]:
plt.figure(figsize=(15,15))
for images, labels in test_generator:
    for i in range (9):
        ax=plt.subplot(3,3,i+1)
        plt.imshow(images[i])

        predicted_class, confidence=predict(model, images[i])
        actual_class=class_names[int(labels[i])]

        plt.title(f"Actual: {actual_class},\n Predicted: {predicted_class},\n Confidence: {confidence}&")
        
        plt.axis("off")
    break

In [ ]:
model.save("../vegetables.h5")